### ISSUE TITLE
Ajouts/modifications de véhicule SP et GN manquant 

### ISSUE THREAD

**Issue by Aurelien06** [Superjajaman75/MOD-CSP-IRG-v2#19]
SP : 

Ajouts :
Epa Bariatrique

VLIMP
HBE
FMOGP

Modifs: 
Remplacer les VSAV Master 2 par des Master 3 dernières générations
Possibilité d'avoir un treuil sur le Dragon 

GN : 

Ajouts : 
Dacia Dusters 
Citroen Berlingo
Skoda karok 
Renault Master 3 GN Mobile
EC-145 GN (Choucas)

Modifs : 

Changer le commissariat de place, si possible 

PS : Serait-il possible d'avoir des interventions plus variers 

Merci par avance

**Comment by Superjajaman75** [comment]
Ajout ==> A voir 
Commissariat ==> A venir dans prochaine MAJ
Intervention ==> Impossible d'en créer plus
