### ISSUE TITLE
Remplacement VSAV 4 CPI

### ISSUE THREAD

**Issue by romingo18** [Superjajaman75/MOD-CSP-IRG-v2#28]
Suggestion : remplacement VSAV 4 du CPI par le VTU du CSP ==> changer les affectations de ces 2 véhicules ?

**Comment by Superjajaman75** [comment]
Tu proposes de les échanger de place ? 
Ou juste mettre le VTU à la place du VSAV4 ?
Dans ce cas la, ou irait le VSAV4 ?

**Comment by romingo18** [comment]
En fait pour être plus clair, je propose de supprimer le VSAV 4 du CPI, mais de le remplacer par le VTU qui est actuellement affecté au CSP ;)

**Comment by PoWerFun91** [comment]
pourquoi faire?

**Comment by romingo18** [comment]
Parce que si je prends l'exemple de mon département (Manche) chaque C.I.S (CPI) et CSP sont dotés d'au moins 1 véhicule d'interventions diverses 😉.
