### ISSUE TITLE
Supprimer quelques buissons haie du CSP

### ISSUE THREAD

**Issue by romingo18** [Superjajaman75/MOD-CSP-IRG-v2#31]
Suggestion : Je propose la suppression de quelques buissons de la grande haie du C.S.P (à proximité du P.C.M), de façon à ce que l'intervention pour départ de feu dure moins longtemps. Car selon mon propre avis, ce départ de feu nécessite beaucoup de temps pour pas grand chose mine de rien. Bien cordialement.

**Comment by Superjajaman75** [comment]
Salut @romingo18 
Nous avons plutôt décidé de de placer plus de PI 😄 

![Emergency 4 Screenshot 2020 04 14 - 19 23 36 08](https://user-images.githubusercontent.com/49571842/79256432-50888e00-7e88-11ea-8a5b-c6279ae1363a.png)

**Comment by romingo18** [comment]
Je n'avais pas vu cette option mais c'est très bien 👌😊
