### ISSUE TITLE
Ajout Canadair CL-415

### ISSUE THREAD

**Issue by romingo18** [Superjajaman75/MOD-CSP-IRG-v2#32]
Bonjour, je propose l'ajout des Canadair CL-415, en remplacement des canadair inclus initialement (Cf. "Bombardier d'eau ABE" dans le jeu). Bonne journée :)

**Comment by Charlieco89** [comment]
Malheureusement la région Hauts de France ne dispose pas de moyen aérien pour éteindre les feux de forêts.
