### ISSUE TITLE
Certains véhicules restent bloqués au commissariat

### ISSUE THREAD

**Issue by fborschneck** [Superjajaman75/MOD-CSP-IRG-v2#33]
Certains véhicules restent bloqués lors de leur entrée ou sortie (Canon CRS notamment) du commissariat. Ce dernier étant en bordure de map, il est très difficile de sélectionner l'engin pour le décoincer.

**Comment by Superjajaman75** [comment]
Sera corrigé dans prochaine version ==> Commissariat déplacé.
