### ISSUE TITLE
Suggestion : modification du nom du "VSAV cube" 

### ISSUE THREAD

**Issue by romingo18** [Superjajaman75/MOD-CSP-IRG-v2#35]
Bonjour, je propose la modification du libellé de la place de remisage du "VSAV cube". En effet, la place du VSAV cube est actuellement nommée "VLI". Or le VSAV cube se rapproche plus d'une Ambulance de Réanimation (A.R) que d'une VLI. Aussi, je propose de renommer le VSAV cube "A.R" (dans le menu déroulant et via le COS pompier).  
Bonne journée :)

**Comment by Superjajaman75** [comment]
Correction du nommage sol CSP prochaine MAJ
