### ISSUE TITLE
Suggestions mod

### ISSUE THREAD

**Issue by Quentin32** [Superjajaman75/MOD-CSP-IRG-v2#36]
Salut ! 
J'aimerais faire 2-3 suggestions comme la croix Rouge que j'adorerais voir ! 1 véhicule de l'armée comme dans le mod los Angeles et ce VSAV 
![IMG_20200515_120847](https://user-images.githubusercontent.com/64707025/82039220-f22c1680-96a4-11ea-95ad-ccd138be903b.jpg)

**Comment by Quentin32** [comment]
Sinon j'adore le mod! 😄😉👍

**Comment by Charlieco89** [comment]
Ce VSAV n'a rien à faire dans le mod, vu qu'il se passe à Douai.
Après si tu parles du châssis Renault Master 3 phase 2, je ne compte pas le faire, car nous avons déjà 4 VSAV et un cube
