### ISSUE TITLE
Command bot proposition

### ISSUE THREAD

**Issue by opium23** [Superjajaman75/MOD-CSP-IRG-v2#37]
salut pourrait tu ajouter des rôles sur le discord par metiers , dans mon cas je voudrais devenir gendarme ( j ai 16 ans ) et donc ça serait super que je puisse poser des questions aux intéressés 
Merci

**Comment by Superjajaman75** [comment]
Salut,
Nous ne voulons pas que les gens partagent leur emploi, c'est la protection de la vie privée.
