### ISSUE TITLE
Bug report 

### ISSUE THREAD

**Issue by opium23** [Superjajaman75/MOD-CSP-IRG-v2#38]
bonjour 
Sur une intervention tentative de suicide sur la rive gauche a droite du csp j'ai descendu la victime a l epa et apres l avoir relâché elle s est effondre et a été déclaré DCD alors que je l avait secouru 
Voilà 🙂

**Comment by Superjajaman75** [comment]
Je viens de tester, il ne doit pas s'agir d'un bug mais d'un mauvais concours de circonstance ^^
