### ISSUE TITLE
Ajout de la Croix Rouge.

### ISSUE THREAD

**Issue by AZO0RQUE3** [Superjajaman75/MOD-CSP-IRG-v2#39]
Bonjour, j'ai vu qu'il y avait un vtp de la crf dans les modèles du mod, alors j'ai essayé d'ajouter l'unité de la croix-rouge en étant fonctionnelle (comme un vsav ou une umh) et je me suis demandé si ce n’était pas possible de l'ajouter officiellement dans le mod pour la prochaine mise à jour. # # #

**Comment by nala56** [comment]
Bonjour merci de votre retours, cette requête nous a déjà été proposer elle est en étude par l'équipe de CSP-IRG

**Comment by Superjajaman75** [comment]
Bonjour,
Nous n'allons pas ajouté la CRF pour le moment.
