### ISSUE TITLE
Bug retour caserne grue + bug erdf

### ISSUE THREAD

**Issue by AZO0RQUE3** [Superjajaman75/MOD-CSP-IRG-v2#41]
Bonjour, je sais pas si c'est que pour moi mais le retour caserne de la grue ne fonctionnait pas. Si c'est pour tout le monde j'ai réussi à le régler dans la ligne 373 du script retour caserne, il manquait à priori un espace entre , VO_SQUADTEC, OBJ_GRUE,

Aussi j'ai remarqué que quand on fait un renfort erdf avec le renfort du cos, il y a une seule place alors qu'avec le renfort via le menu déroulant il y avait deux places dans le véhicule. A priori ca viendrait de la ligne 1942 du script renfort où il y a marqué 1 à la place de 2 dans 
ClassRenfort::Renfort(Caller, Game::GetCommandPos(), PROTO_EDF, VT_THW_FGRI_EKW, sNULL, personnelVehicule, **2**, 0);

voila voila

**Comment by nala56** [comment]
Bonjour, 
Pour le bug retour de la grue effectivement il y a un problème. Merci de ton retour.

Cependant pour le véhicule ERDF tout ceci est normal et voulu pour plus de réalisme comme pour la Mégane RS qui doit être équipée de 2 places.

Cordialement
Nala

**Comment by AZO0RQUE3** [comment]
D'accord ca marche mais du coup c'est pas pratique quand on doit évacuer un technicien qui a perdu son véhicule

**Comment by Superjajaman75** [comment]
Il n'y a pas de bug pour le retour caserne de la grue.
Le c++ n'est pas sensible aux espaces dans les paramètres de fonction.
Le delta des places assises a été corrigé en version dev.
