### ISSUE TITLE
Crash retour bureau moto

### ISSUE THREAD

**Issue by JulesWall** [Superjajaman75/MOD-CSP-IRG-v2#42]
Lors de l'utilisation des motos (pn/gn), il existe un crash retour bureau au moment où on fait descendre le policier de la moto (celui-ci n'est pas systématique et dans la majorité des cas le jeux ne crash pas).

**Comment by nala56** [comment]
Bonjour Jules, 
Merci de ton retour, ce problème est déjà connu de nos équipes. 
Une résolution est en cours de recherche.

Cordialement
Nala

**Comment by Superjajaman75** [comment]
Duplicata https://github.com/Superjajaman75/MOD-CSP-IRG/issues/10
