### ISSUE TITLE
Sniper GN et IVECO

### ISSUE THREAD

**Issue by JulesWall** [Superjajaman75/MOD-CSP-IRG-v2#43]
Salut ^^

Je viens de me rendre compte que l'icone "viser" et "end aim" (j'ai plus le nom français en tête) sont inversé lorsque les snipers GN sont en mode visée. Celui pour viser a la croix rouge et inversement.

Aussi l'iveco semble avoir une vie infinie en free play (j'ai test celui du menu COS et celui de menu classique) et la vie (ou du moins l'affichage ne jeux) ne baisse pas malgré plusieurs dizaines de gendarmes tirant dessus pendant plus d'une minutes.

Voilà deux petits bugs que j'ai testé de mon coté :p rien de bien foufou mais voilà.
Autant fix ça avec LA SURPRISE (👀)

Allez bisous.

**Comment by nala56** [comment]
Bonjour Jules,
Tout d'abord merci de ton retour.
Alors Premièrement pour les véhicules de gendarmerie mobile rien d’anormal. En effet les véhicules de gendarmerie et police sont normalement "blindés" voilà pourquoi nous ne pouvons pas les détruire.
Et deuxièmement pour la viser du sniper GN je remonte l'information aux personnes concernées

Cordialement 
Nala

**Comment by Superjajaman75** [comment]
Icônes corrigés dans la version dev.

On uniformisera les protections de véhicule.
