### ISSUE TITLE
Suggestion : Police / Gendarmerie

### ISSUE THREAD

**Issue by nedyfr** [Superjajaman75/MOD-CSP-IRG-v2#47]
Qu'après avoir emmener un suspect au commissariat, que les effectifs ressortent du commissariat pour reprendre leur patrouille. Car actuellement les véhicules restent devant le commissariat vides, et nécessitent d'être supprimés à la main...

**Comment by nedyfr** [comment]
Egalement, le BUS DE CRS et le canon à eau CRS ont du mal à sortir du commissariat

**Comment by Superjajaman75** [comment]
> Qu'après avoir emmener un suspect au commissariat, que les effectifs ressortent du commissariat pour reprendre leur patrouille. Car actuellement les véhicules restent devant le commissariat vides, et nécessitent d'être supprimés à la main...

Il faut les rappeler pour les faire sortir avec le COS
Si vous ne savez utiliser le COS, reportez vous au manuel ou aux multiples vidéos sur YouTube.

> Également, le BUS DE CRS et le canon à eau CRS ont du mal à sortir du commissariat

Pris en compte dans prochaine MAJ, utiliser le COS et non le menu latéral en attendant.
