### ISSUE TITLE
Changement de pleins de truc

### ISSUE THREAD

**Issue by ANT91790Officiel** [Superjajaman75/MOD-CSP-IRG-v2#49]
Bonjour je peut vous conseiller pleins de trucs s'il vous plaît ? 
1 : Mettre tout les véhicules de police sauf les le bus ni le camion a eau et ni les fourgons en patrouille
2 : Mettre tout les véhicules de gendarmerie sauf les fourgons en patrouille 
3 : Mettre tout les véhicules de pompier de sauvetage en patrouille
4 : Mettre tout les véhicules de samu de sauvetage en patrouille 
Comme sa quand ils reviennent d intervention il peuvent patrouiller pour être plus proche des interventions :)

**Comment by Superjajaman75** [comment]
1&2 OK
3&4 ==> non pas RP

**Comment by Superjajaman75** [comment]
1&2 fait sur la mise à jour
