### ISSUE TITLE
Suggestion - Patrouille des patrouilleurs sanef

### ISSUE THREAD

**Issue by Tiennou57** [Superjajaman75/MOD-CSP-IRG-v2#50]
Il sera bien d'ajouter la fonction "patrouille" aux patrouilleurs. Leurs laissant la possibilité de faire des rondes sur des axes routiers important

**Comment by Superjajaman75** [comment]
A voir des chemins précis a faire sur la nouvelle map autoroute qui arrive

**Comment by Superjajaman75** [comment]
Au vu de la configuration de la map, on a essayé et ça fera faire des patrouilles sur une sortie => pas intéressant de tourner en rond
