### ISSUE TITLE
Missions en bordure de map

### ISSUE THREAD

**Issue by Alanomarco** [Superjajaman75/MOD-CSP-IRG-v2#52]
Hello,

Par pitié, serait-il possible d'éviter de générer des missions en bordure de map ?
Quand il s'agit de feux, c'est incontrôlable ; pour les criminels, il leur suffit de 5sec pour quitter la map ; etc...

Merci :+1:

**Comment by Charlieco89** [comment]
Malheureusement il ne sera pas possible d'éviter ce problème. Le jeu génère aléatoirement les incendies.
