### ISSUE TITLE
nouvelle caserne

### ISSUE THREAD

**Issue by sacha02** [Superjajaman75/MOD-CSP-IRG-v2#54]
bonjour j'aimerais pour la prochaine maj voir une nouvelle caserne ca serait super
merci

**Comment by Charlieco89** [comment]
Bonjour, 
Le CSP dans le mod CSP-IRG est celui de Douai, le mod se déroule à Douai.
Donc, non, nous ne le modifierons pas. Et nous n'en ajouterons pas non plus.
