### ISSUE TITLE
Régler des bug et amélioration de caserne

### ISSUE THREAD

**Issue by NTFespolion307** [Superjajaman75/MOD-CSP-IRG-v2#57]
Régler des bug:

Dans la grosse caserne les deux VLM des sapeur pompier ne son pas a la bonne place il faut les inverser car si je fais retour caserne il von glitch l'une dans l'autre, au début dune partie il faut appeler les deux VLM des sapeur pompier avec le COS et après fais retour caserne pour qu'il ailles a la bonne place.
____________________________________________________________________________________________________________________________________

Amélioration de caserne:

Dans la caserne pour les feux de forêt il faudrait faire un CCF1, CCF2 et CCF3 et garder le CCF lourd car quand on fais un GIFF il y a trois CCF qui arrive, un dans la caserne et deux dans le (HQ). il faudrait faire cela pourrais améliorer le RP du jeux car les CCF n'apparaitront plus de nul part mais dans la caserne pour les feu de forêt.

De: NTFespolion307

**Comment by Superjajaman75** [comment]
Bug résolu dans : https://github.com/Superjajaman75/MOD-CSP-IRG/issues/9 
La "caserne feu de foret" est un CPI, elle ne fait pas que du feu de foret
