### ISSUE TITLE
Bug Réparation Des Vehicules Interventions

### ISSUE THREAD

**Issue by NickyEqueen** [Superjajaman75/MOD-CSP-IRG-v2#60]
j'ai découvert un Bug :D  

Lorsque l'on utilise l'agent ERDF pour réparer les Vehicules d'intervention endommagés le Jeu Crash

J'ai fais quelques Tests et il s'avère que lorsque l'on fait clique droit (icone de main par défaut) directement sur l'un des vehicules citez ci-dessous le jeu Crash, (oui c'est étrange mais certains VSAV ne sont pas concerner, la liste est juste je n'ai rien oublier) 
En revanche si on utilise l'icone de Clé à molette dans l'inventaire du technicien le vehicule peut être réparer sans que le jeu ne crash 

La Liste des véhicules concerner sont : 
-EPA
-VTP
-VPL
-PMA
-VSAV HR
-VSAV 1 (Renault Master)
-VSAV 2 (Citroen Jumper)
-VSS

PS : J'ai aussi remarqué que le nom du véhicule 2 des PF ne s'affiche pas correctement, à la place c'est écrit : ID_PORTRAIT_PF_FOURGON2

Voilà Voilà :D

**Comment by Charlieco89** [comment]
Merci pour ton retour.
Nous regarderons pour résoudre ce bug.
