### ISSUE TITLE
Nouvelle idée

### ISSUE THREAD

**Issue by djm-4** [Superjajaman75/MOD-CSP-IRG-v2#61]
Bonjour,

Je vous propose de nouvelle idée a rajouter au mod

- Equipe cynotechnique pour les force de l'ordre et sp pour les recherches
- Police judiciaire
- changer le nom de la voiture edf par grdf car c'est une voiture d'intervention pour le gaz et pas edf
- Ajouter une VL EDF
- Nouvelle voiture de police 5008

**Comment by Superjajaman75** [comment]
Cyno => OK MAJ
PJ => pas d'interet dans le MOD sans ajouter un script, on garde l'idée
EDF / GRDF => TODO
5008 => non, mais on a fait autre chose à la place dans la MAJ. A voir pour la 3008/5008
