### ISSUE TITLE
Bug retour caserne

### ISSUE THREAD

**Issue by StevenSoulet** [Superjajaman75/MOD-CSP-IRG-v2#62]
Bonjour, je signale deux soucis que je ne vois pas sur le github : 
- Lors d'un retour caserne du VSAV 2, le secouriste reste à l'interieur
- Lors d'un retour caserne du VLI, il rentre et se met sur la place à coté, celle du EMOD.

**Comment by nala56** [comment]
Bonjour,

Merci de ton retour, les bugs signalés sont déjà connus de l'équipe et corrigés dans la prochaine mise à jour.
