### ISSUE TITLE
ford focus gendarmerie

### ISSUE THREAD

**Issue by thebigflag** [Superjajaman75/MOD-CSP-IRG-v2#63]
bouton "patrouille" inexistant sur la ford focus de la gendarmerie

**Comment by nala56** [comment]
Bonjour 
Effectivement, la patrouille n'est pas disponible, car il s'agit d'un véhicule d'interception comme la Mégane-RS ou la Subaru.

**Comment by thebigflag** [comment]
je vois
________________________________
De : nala56 ***@***.***>
Envoyé : jeudi 25 août 2022 11:24
À : Superjajaman75/MOD-CSP-IRG ***@***.***>
Cc : thebigflag ***@***.***>; State change ***@***.***>
Objet : Re: [Superjajaman75/MOD-CSP-IRG] ford focus gendarmerie (Issue #63)


Bonjour
Effectivement, la patrouille n'est pas disponible, car il s'agit d'un véhicule d'interception comme la Mégane-RS ou la Subaru.
