### ISSUE TITLE
lance à incendie depuis vehicule

### ISSUE THREAD

**Issue by thebigflag** [Superjajaman75/MOD-CSP-IRG-v2#64]
la lance à incendie quand elle est branchée a un vehicule de pompier, meme si celui ci est plein, ne fonctionne pas

**Comment by nala56** [comment]
Bonjour avez vous mis un pompier pour alimenté la pompe de l'engin ?

**Comment by thebigflag** [comment]
non, je comprends maintenant mon erreur
________________________________
De : nala56 ***@***.***>
Envoyé : jeudi 25 août 2022 11:15
À : Superjajaman75/MOD-CSP-IRG ***@***.***>
Cc : thebigflag ***@***.***>; Author ***@***.***>
Objet : Re: [Superjajaman75/MOD-CSP-IRG] lance à incendie depuis vehicule (Issue #64)


Bonjour avez vous mis un pompier pour alimenté la pompe de l'engin ?
