### ISSUE TITLE
Idée pour le système de synoptique

### ISSUE THREAD

**Issue by Ralgrim66** [Superjajaman75/MOD-CSP-IRG-v2#68]
A l'heure actuelle on a accès au CSP de Douai et au CPI Sin le Noble, mais avec le synoptique j'ai pensé qu'on aurait pu rajouter des casernes externes à la map, un peu comme sur certains mods allemand si je ne me trompe pas.

En gros cela rajouterai du réalisme en partie et au lieu de se retrouver à envoyer 40 CCF inexistants on pourrai en priorité chercher des CCR et CCF dans certains centres externes. Je prend l'exemple des moyens pour les feux de végétation, mais même pour les moyens urbains et spécialité cela serai intéressant à mon avis.

De plus en cas de présence en partie multi d'un joueur CTA/CODIS, il pourrai vraiment pousser à bout le réalisme en cas de grosse inter et faire appel à des moyens plus précis (des moyens de Lille ou autres).

Comme dit dans le général hier soir, cela ne reste qu'une idée pouvant rajouter du réalisme mais je sais pas si c'est faisable, je trouvais juste cela cool en vue des "spoils" qu'on a pu apercevoir. 
Encore merci pour tout et courage à toute l'équipe.

**Comment by Superjajaman75** [comment]
Pris en compte, mais pas sur que ce soit faisable sur la partie "gestion de moyen extérieurs"
